site_name: SciPipe Docs
theme: material
pages:
  - 'SciPipe Overview': 'index.md'
  - 'Installing SciPipe': 'install.md'
  - 'Writing Workflows': 'writing_workflows.md'
  - 'Examples': 'examples.md'
repo_name: 'scipipe/scipipe'
repo_url: 'https://github.com/scipipe/scipipe'
extra:
    logo: 'images/scipipe_logo_bluegrey.svg'
    palette:
        primary: 'blue grey'
        accent: 'cyan'
    social:
        - type: 'github'
          link: 'https://github.com/scipipe'
        - type: 'twitter'
          link: 'https://twitter.com/scipipe'
        - type: 'linkedin'
          link: 'https://www.linkedin.com/in/samuellampa/'
markdown_extensions:
  - codehilite
extra_css: ['custom.css']
